### PR TITLE
Add support for Graph API

### PR DESCRIPTION
**Pull request by stevenjonescgm**
Microsoft is deprecating the Outlook API, in favor of the Graph API.

These changes add support for using various API endpoints and versions.
To minimize impact in upgrade, the defined resource operations also support transforming keys between camelCase (Graph API) and PascalCase (Outlook API)

This PR also DRY's request setup and parsing as well as updates tests.

### CODE REVIEW

**Comment by jasonjoh** [comment]
This looks great! To be honest I have not been maintaining this repository since Outlook APIs are de-emphasized. Can I ask: are you actively using this in a solution?

**Comment by jasonjoh** [comment]
Also, do you have this box unchecked? I'm trying to resolve a merge conflict but your fork is not letting me push the merge:

image

**Comment by stevenjonescgm** [comment]
ah, thanks. I actually was intending to make the PR target our fork and continue testing before making the upstream PR, but GitHub UI/UX 🤷  I was having trouble with Bundler finding the branch and commit ref until I merged it to RepairShopr:master

We are actively using the gem and I was refreshing the integration when I saw the Outlook API docs forwarding to Graph API so I decided to extend the gem rather than layer on top or replace. We're not ready to switch over to Graph yet, so that part is not actively tested but does pass the tests (Except I skipped the Mail tests, I did not need that feature and didn't bother adding the necessary OAuth scope)

I did not find the 'Allow edits by maintainers' box, so I resolved the conflicts myself.

**Comment by jasonjoh** [comment]
Awesome, I'm glad to hear. Hopefully at some point we will have an official Graph Ruby SDK :)

**Pull request merged**
