### PR TITLE
Files in the bin/ folder: Permission +x

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR makes the bin/ files executable.

### CODE REVIEW

**Comment by jasonjoh** [comment]
Thanks @olleolleolle! GitHub isn't registering any changes in your pull request. Did you have to change something to get it to work on your system? What did you do, and on what OS?

**Comment by olleolleolle** [comment]
@jasonjoh Oh the detail is a little subtle. 

The changes to permissions on the files are shown as octal numbers changing. 

The change is only the executable flag on the files that ought to be executable.

**Comment by olleolleolle** [comment]
100644 -> 100755 is the number to look for in the space where the name of the file is listed, in the Files Changed tab of this PR. 

Hope this helps!

**Comment by jasonjoh** [comment]
Got it. Thanks!

**Pull request merged**
